/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/salary/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate net salary from gross annual salary */
        post: operations["calculateNetSalary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/costs/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estimate living costs for a Berlin neighborhood */
        get: operations["estimateCosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all Berlin neighborhood profiles */
        get: operations["getAllNeighborhoods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods/{bezirk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific Berlin neighborhood profile */
        get: operations["getNeighborhood"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description German tax classes (Steuerklassen I-VI)
         * @enum {string}
         */
        TaxClass: "I" | "II" | "III" | "IV" | "V" | "VI";
        /** @enum {string} */
        Bezirk: "mitte" | "friedrichshain-kreuzberg" | "pankow" | "charlottenburg-wilmersdorf" | "spandau" | "steglitz-zehlendorf" | "tempelhof-schoeneberg" | "neukoelln" | "treptow-koepenick" | "marzahn-hellersdorf" | "lichtenberg" | "reinickendorf";
        SalaryRequest: {
            /** @description Gross annual salary in EUR */
            grossAnnual: number;
            taxClass: components["schemas"]["TaxClass"];
            /** @default false */
            churchTax: boolean;
            /** @default false */
            hasChildren: boolean;
            /** @default 0 */
            childCount: number;
            /** @default 18 */
            respondentAge: number;
        };
        SalaryResponse: {
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            grossMonthly: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            netMonthly: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            incomeTax: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            solidaritySurcharge: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            healthInsurance: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            pensionInsurance: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            unemploymentInsurance: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            nursingCareInsurance: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            churchTaxAmount: ((number | null) | null) | null;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            totalDeductions: number;
        };
        RentRange: {
            /** Format: double */
            min: number;
            /** Format: double */
            max: number;
            /** Format: double */
            median: number;
        };
        CostEstimate: {
            bezirk: components["schemas"]["Bezirk"];
            displayName: string;
            rooms: number;
            rentRange: components["schemas"]["RentRange"];
            /** Format: double */
            utilities: number;
            /** Format: double */
            transport: number;
            /** Format: double */
            groceries: number;
            /** Format: double */
            totalEstimated: number;
        };
        NeighborhoodProfile: {
            bezirk: components["schemas"]["Bezirk"];
            displayName: string;
            vibe: string;
            commuteMinutes: number;
            highlights: string[];
        };
        ApiError: {
            status: number;
            message: string;
            /** Format: date-time */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    calculateNetSalary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalaryRequest"];
            };
        };
        responses: {
            /** @description Successful salary calculation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalaryResponse"];
                };
            };
        };
    };
    estimateCosts: {
        parameters: {
            query: {
                bezirk: string;
                rooms?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful cost estimation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostEstimate"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getAllNeighborhoods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all neighborhood profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeighborhoodProfile"][];
                };
            };
        };
    };
    getNeighborhood: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bezirk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Neighborhood profile found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeighborhoodProfile"];
                };
            };
            /** @description Neighborhood not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
