/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/salary/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate net salary from gross annual salary */
        post: operations["calculateNetSalary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/costs/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estimate living costs for a Berlin neighborhood */
        get: operations["estimateCosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/costs/allocate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Construct a budget and return Bezirk-specific information on line-items */
        post: operations["allocateBudget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/costs/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Collects all relevant context about chosen bezirk and budget choices, sends to AI for analysis, and returns a description of life with the user's choices */
        post: operations["analyzeSelections"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all Berlin neighborhood profiles */
        get: operations["getAllNeighborhoods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods/{bezirk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific Berlin neighborhood profile */
        get: operations["getNeighborhood"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description German tax classes (Steuerklassen I-VI)
         * @enum {string}
         */
        TaxClass: "I" | "II" | "III" | "IV" | "V" | "VI";
        /** @enum {string} */
        Bezirk: "mitte" | "friedrichshain-kreuzberg" | "pankow" | "charlottenburg-wilmersdorf" | "spandau" | "steglitz-zehlendorf" | "tempelhof-schoeneberg" | "neukoelln" | "treptow-koepenick" | "marzahn-hellersdorf" | "lichtenberg" | "reinickendorf";
        SalaryRequest: {
            /** @description Gross annual salary in EUR */
            grossAnnual: number;
            taxClass: components["schemas"]["TaxClass"];
            /** @default false */
            churchTax: boolean;
            /** @default false */
            hasChildren: boolean;
            /** @default 0 */
            childCount: number;
            /** @default 18 */
            respondentAge: number;
        };
        SalaryResponse: {
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            grossMonthly: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            netMonthly: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            incomeTax: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            solidaritySurcharge: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            healthInsurance: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            pensionInsurance: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            unemploymentInsurance: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            nursingCareInsurance: number;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            churchTaxAmount: number | null;
            /**
             * Format: double
             * @description Monthly amount in EUR
             */
            totalDeductions: number;
            incomeBreakdown: components["schemas"]["IncomeTaxBreakdown"];
        };
        IncomeTaxBreakdown: {
            /**
             * Format: double
             * @description Gross annual salary (echoed for display context)
             */
            grossAnnual: number;
            /**
             * Format: double
             * @description Zu versteuerndes Einkommen — taxable income after all deductions
             */
            zvE: number;
            /** @description The five zones of the German progressive tax formula, in fixed order: [Grundfreibetrag, Zone 1, Zone 2, Spitzensteuersatz, Reichensteuer]. */
            brackets: components["schemas"]["TaxBracket"][];
            /**
             * Format: double
             * @description Total annual income tax before employee deductions
             */
            einkommensteuerAnnual: number;
            /**
             * Format: double
             * @description einkommensteuerAnnual / 12
             */
            einkommensteuerMonthly: number;
            /**
             * Format: double
             * @description Annual provision allowance (reduces taxable income)
             */
            vorsorgepauschale: number;
            /**
             * Format: double
             * @description Employee expense lump sum (1.230 EUR for 2026)
             */
            werbungskosten: number;
            /**
             * Format: double
             * @description Special expenses flat deduction (36 EUR for 2026)
             */
            sonderausgaben: number;
            /**
             * Format: double
             * @description Final monthly wage tax after all deductions
             */
            lohnsteuerMonthly: number;
        };
        TaxBracket: {
            /**
             * @description Bracket name, one of the five progressive tax zones
             * @enum {string}
             */
            name: "Grundfreibetrag" | "Zone 1" | "Zone 2" | "Spitzensteuersatz" | "Reichensteuer";
            /**
             * @description Inclusive lower bound of the bracket in EUR
             * @example 0
             */
            lowerBound: number;
            /**
             * @description Inclusive upper bound in EUR, null for the open-ended top bracket
             * @example 12348
             */
            upperBound: number | null;
            /**
             * @description Tax rate or rate range for this bracket (e.g. "0%", "14–24%", "42%")
             * @example 0%
             */
            rate: string;
            /**
             * Format: double
             * @description Tax owed within this bracket for the given income
             * @example 0
             */
            taxAmount: number;
        };
        RentRange: {
            /** Format: double */
            min: number;
            /** Format: double */
            max: number;
            /** Format: double */
            median: number;
        };
        CostEstimate: {
            bezirk: components["schemas"]["Bezirk"];
            displayName: string;
            rooms: number;
            rentRange: components["schemas"]["RentRange"];
            /** Format: double */
            utilities: number;
            /** Format: double */
            transport: number;
            /** Format: double */
            groceries: number;
            /** Format: double */
            totalEstimated: number;
        };
        BudgetAllocationRequest: {
            /** Format: float */
            netMonthlySalary: number;
            bezirk: components["schemas"]["Bezirk"];
            rooms: number;
            categories: components["schemas"]["BudgetCategoryInput"][];
        };
        BudgetCategoryInput: {
            key: string;
            label: string;
            /** Format: float */
            percentage: number;
            isCustom: boolean;
        };
        BudgetAllocation: {
            /** Format: float */
            netMonthlySalary: number;
            bezirk: components["schemas"]["Bezirk"];
            rooms: number;
            categories: components["schemas"]["BudgetCategory"][];
        };
        BudgetCategory: {
            key: string;
            label: string;
            /** Format: float */
            percentage: number;
            /** Format: float */
            total: number;
            isCustom: boolean;
            pieGroup: string;
            recommendedState?: {
                /** Format: double */
                minTotal?: number;
                /** Format: float */
                percentage?: number;
            } | null;
        };
        AnalysisContext: {
            /**
             * Format: double
             * @description Monthly take-home pay after all deductions
             */
            netMonthlySalary: number;
            /** @description Gross annual salary in EUR (for context on career level) */
            grossAnnualSalary: number;
            taxClass: components["schemas"]["TaxClass"];
            bezirk: components["schemas"]["Bezirk"];
            /** @description Human-readable Bezirk name (e.g. "Friedrichshain-Kreuzberg") */
            bezirkDisplayName?: string;
            /** @description Number of rooms in the apartment */
            rooms: number;
            /** @description Full budget allocation with percentages and EUR amounts */
            categories: components["schemas"]["BudgetCategory"][];
            /**
             * Format: double
             * @description Sum of all category EUR amounts
             */
            totalAllocated?: number;
            /**
             * Format: double
             * @description Net salary minus total allocated (can be negative)
             */
            remainingMonthly?: number;
            rentRange: components["schemas"]["RentRange"];
            /** @description The Bezirk's vibe description from neighborhood profile */
            neighborhoodVibe: string;
            /** @description Key highlights of the chosen Bezirk */
            neighborhoodHighlights?: string[];
            hasChildren?: boolean;
            childCount?: number;
        };
        BudgetAnalysis: {
            /** @description Structured narrative sections for display */
            sections: components["schemas"]["AnalysisSection"][];
            /** Format: date-time */
            generatedAt: string;
        };
        AnalysisSection: {
            /**
             * @description Section identifier for styling/icons
             * @enum {string}
             */
            key: "daily-life" | "housing" | "food-and-dining" | "transport-and-mobility" | "leisure-and-culture" | "financial-health" | "tips";
            /** @description Display heading for the section */
            heading: string;
            /** @description Markdown-formatted narrative content */
            body: string;
            /**
             * @description Overall tone of this section, for visual treatment
             * @enum {string}
             */
            sentiment?: "positive" | "neutral" | "caution";
        };
        NeighborhoodProfile: {
            bezirk: components["schemas"]["Bezirk"];
            displayName: string;
            vibe: string;
            /** @description Minimum commute time to Mitte (Alexanderplatz) by public transit */
            commuteMinutesMin: number;
            /** @description Maximum commute time to Mitte from the furthest parts of the district */
            commuteMinutesMax: number;
            highlights: string[];
        };
        ApiError: {
            status: number;
            message: string;
            /** Format: date-time */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    calculateNetSalary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalaryRequest"];
            };
        };
        responses: {
            /** @description Successful salary calculation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalaryResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    estimateCosts: {
        parameters: {
            query: {
                bezirk: string;
                rooms?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful cost estimation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostEstimate"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    allocateBudget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetAllocationRequest"];
            };
        };
        responses: {
            /** @description Successful budget allocation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetAllocation"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    analyzeSelections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisContext"];
            };
        };
        responses: {
            /** @description Successful AI-generated budget analysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetAnalysis"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getAllNeighborhoods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all neighborhood profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeighborhoodProfile"][];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getNeighborhood: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bezirk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Neighborhood profile found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeighborhoodProfile"];
                };
            };
            /** @description Neighborhood not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
