import type { SalaryResponse } from '../../models/salary.model';
import type { CostEstimate, NeighborhoodProfile } from '../../models/cost.model';
import type { BudgetAllocation } from '../../models/budget.model';

export const SALARY_SINGLE: SalaryResponse = {
  grossMonthly: 6250.0,
  netMonthly: 3811.46,
  incomeTax: 1180.26,
  solidaritySurcharge: 0.0,
  healthInsurance: 473.72,
  pensionInsurance: 581.25,
  unemploymentInsurance: 81.25,
  nursingCareInsurance: 122.06,
  churchTaxAmount: null,
  totalDeductions: 2438.54,
  incomeBreakdown: {
    grossAnnual: 75000.0,
    zvE: 59818.0,
    brackets: [
      { name: 'Grundfreibetrag', lowerBound: 0, upperBound: 12348, rate: '0%', taxAmount: 0.0 },
      { name: 'Zone 1', lowerBound: 12349, upperBound: 17799, rate: '14–24%', taxAmount: 1034.87 },
      { name: 'Zone 2', lowerBound: 17800, upperBound: 69878, rate: '24–42%', taxAmount: 13128.2 },
      {
        name: 'Spitzensteuersatz',
        lowerBound: 69879,
        upperBound: 277825,
        rate: '42%',
        taxAmount: 0.0,
      },
      { name: 'Reichensteuer', lowerBound: 277826, upperBound: null, rate: '45%', taxAmount: 0.0 },
    ],
    einkommensteuerAnnual: 14163.07,
    einkommensteuerMonthly: 1180.26,
    vorsorgepauschale: 13916.0,
    werbungskosten: 1230.0,
    sonderausgaben: 36.0,
    lohnsteuerMonthly: 1180.26,
  },
};

export const SALARY_MARRIED: SalaryResponse = {
  grossMonthly: 10000.0,
  netMonthly: 6443.46,
  incomeTax: 1844.15,
  solidaritySurcharge: 101.43,
  healthInsurance: 473.72,
  pensionInsurance: 785.85,
  unemploymentInsurance: 109.85,
  nursingCareInsurance: 75.56,
  churchTaxAmount: 165.97,
  totalDeductions: 3556.54,
  incomeBreakdown: {
    grossAnnual: 120000.0,
    zvE: 102921.0,
    brackets: [
      { name: 'Grundfreibetrag', lowerBound: 0, upperBound: 12348, rate: '0%', taxAmount: 0.0 },
      { name: 'Zone 1', lowerBound: 12349, upperBound: 17799, rate: '14–24%', taxAmount: 2069.74 },
      { name: 'Zone 2', lowerBound: 17800, upperBound: 69878, rate: '24–42%', taxAmount: 20060.1 },
      {
        name: 'Spitzensteuersatz',
        lowerBound: 69879,
        upperBound: 277825,
        rate: '42%',
        taxAmount: 0.0,
      },
      { name: 'Reichensteuer', lowerBound: 277826, upperBound: null, rate: '45%', taxAmount: 0.0 },
    ],
    einkommensteuerAnnual: 22129.84,
    einkommensteuerMonthly: 1844.15,
    vorsorgepauschale: 15813.0,
    werbungskosten: 1230.0,
    sonderausgaben: 36.0,
    lohnsteuerMonthly: 1844.15,
  },
};

export const SALARY_LOW: SalaryResponse = {
  grossMonthly: 1000.0,
  netMonthly: 791.5,
  incomeTax: 0.0,
  solidaritySurcharge: 0.0,
  healthInsurance: 81.5,
  pensionInsurance: 93.0,
  unemploymentInsurance: 13.0,
  nursingCareInsurance: 21.0,
  churchTaxAmount: null,
  totalDeductions: 208.5,
  incomeBreakdown: {
    grossAnnual: 12000.0,
    zvE: 8268.0,
    brackets: [
      { name: 'Grundfreibetrag', lowerBound: 0, upperBound: 12348, rate: '0%', taxAmount: 0.0 },
      { name: 'Zone 1', lowerBound: 12349, upperBound: 17799, rate: '14–24%', taxAmount: 0.0 },
      { name: 'Zone 2', lowerBound: 17800, upperBound: 69878, rate: '24–42%', taxAmount: 0.0 },
      {
        name: 'Spitzensteuersatz',
        lowerBound: 69879,
        upperBound: 277825,
        rate: '42%',
        taxAmount: 0.0,
      },
      { name: 'Reichensteuer', lowerBound: 277826, upperBound: null, rate: '45%', taxAmount: 0.0 },
    ],
    einkommensteuerAnnual: 0.0,
    einkommensteuerMonthly: 0.0,
    vorsorgepauschale: 2466.0,
    werbungskosten: 1230.0,
    sonderausgaben: 36.0,
    lohnsteuerMonthly: 0.0,
  },
};

export const COST_MITTE: CostEstimate = {
  bezirk: 'mitte',
  displayName: 'Mitte',
  rooms: 2,
  rentRange: { min: 770.0, max: 1210.0, median: 962.5 },
  utilities: 192.5,
  transport: 58.0,
  groceries: 300.0,
  totalEstimated: 1513.0,
};

export const COST_SPANDAU: CostEstimate = {
  bezirk: 'spandau',
  displayName: 'Spandau',
  rooms: 3,
  rentRange: { min: 680.0, max: 1040.0, median: 840.0 },
  utilities: 280.0,
  transport: 58.0,
  groceries: 300.0,
  totalEstimated: 1478.0,
};

export const COST_FHXBG: CostEstimate = {
  bezirk: 'friedrichshain-kreuzberg',
  displayName: 'Friedrichshain-Kreuzberg',
  rooms: 1,
  rentRange: { min: 455.0, max: 700.0, median: 560.0 },
  utilities: 122.5,
  transport: 58.0,
  groceries: 300.0,
  totalEstimated: 1040.5,
};

export const NEIGHBORHOODS: NeighborhoodProfile[] = [
  {
    bezirk: 'mitte',
    displayName: 'Mitte',
    vibe: 'The historic and governmental heart of Berlin. Tourist-heavy but culturally rich.',
    commuteMinutesMin: 5,
    commuteMinutesMax: 25,
    highlights: [
      'Museum Island & Brandenburg Gate',
      'Excellent transit connections (U/S-Bahn hub)',
      'International dining scene',
      'High density of coworking spaces',
      'Expensive but central',
    ],
  },
  {
    bezirk: 'friedrichshain-kreuzberg',
    displayName: 'Friedrichshain-Kreuzberg',
    vibe: "Berlin's creative and nightlife epicenter. Diverse, vibrant, sometimes chaotic.",
    commuteMinutesMin: 6,
    commuteMinutesMax: 20,
    highlights: [
      'Best nightlife in Berlin (Berghain, RAW area)',
      'Multicultural food scene (Turkish Market, Markthalle Neun)',
      'Strong startup and tech community',
      'Beautiful Landwehrkanal for walks',
      'Highly competitive rental market',
    ],
  },
  {
    bezirk: 'pankow',
    displayName: 'Pankow',
    vibe: 'Family-friendly with a village feel. Prenzlauer Berg is the gentrified gem within.',
    commuteMinutesMin: 11,
    commuteMinutesMax: 35,
    highlights: [
      "Prenzlauer Berg's café culture and boutiques",
      'Mauerpark Sunday flea market and karaoke',
      'Excellent schools and playgrounds',
      'Green spaces (Volkspark Friedrichshain nearby)',
      'More affordable than Mitte with similar quality',
    ],
  },
  {
    bezirk: 'charlottenburg-wilmersdorf',
    displayName: 'Charlottenburg-Wilmersdorf',
    vibe: 'Old West Berlin elegance. Upscale, quiet, with grand architecture.',
    commuteMinutesMin: 12,
    commuteMinutesMax: 30,
    highlights: [
      'Kurfürstendamm shopping boulevard',
      'Charlottenburg Palace and gardens',
      'Excellent international schools',
      'Quieter, more residential atmosphere',
      'Strong expat community',
    ],
  },
  {
    bezirk: 'spandau',
    displayName: 'Spandau',
    vibe: 'A city within a city. Affordable, green, and feels separate from Berlin.',
    commuteMinutesMin: 25,
    commuteMinutesMax: 55,
    highlights: [
      'Most affordable rents in Berlin',
      'Spandau Citadel (medieval fortress)',
      'Surrounded by rivers and forests',
      'Good for families wanting space',
      'Longer commute to central Berlin',
    ],
  },
  {
    bezirk: 'steglitz-zehlendorf',
    displayName: 'Steglitz-Zehlendorf',
    vibe: 'Leafy, suburban, and academic. Home to Freie Universität.',
    commuteMinutesMin: 25,
    commuteMinutesMax: 45,
    highlights: [
      'Botanical Garden Berlin',
      'Krumme Lanke and Schlachtensee lakes',
      'University district atmosphere',
      'Very safe and family-friendly',
      'Good balance of price and quality',
    ],
  },
  {
    bezirk: 'tempelhof-schoeneberg',
    displayName: 'Tempelhof-Schöneberg',
    vibe: 'Diverse and welcoming. Historic LGBTQ+ neighborhood with great parks.',
    commuteMinutesMin: 15,
    commuteMinutesMax: 30,
    highlights: [
      'Tempelhofer Feld (former airport, now massive park)',
      "Schöneberg's vibrant LGBTQ+ scene",
      'Good mix of cultures and cuisines',
      'Reasonable rents for central location',
      'Excellent U-Bahn connections',
    ],
  },
  {
    bezirk: 'neukoelln',
    displayName: 'Neukölln',
    vibe: 'Rapidly gentrifying but still gritty. Art galleries meet döner shops.',
    commuteMinutesMin: 11,
    commuteMinutesMax: 30,
    highlights: [
      'Thriving art and music scene',
      'Incredible food diversity',
      'Tempelhofer Feld access',
      'More affordable than Kreuzberg (barely)',
      '48-hour Neukölln arts festival',
    ],
  },
  {
    bezirk: 'treptow-koepenick',
    displayName: 'Treptow-Köpenick',
    vibe: "Berlin's green lung. Lakes, forests, and a small-town feel.",
    commuteMinutesMin: 15,
    commuteMinutesMax: 45,
    highlights: [
      "Müggelsee (Berlin's largest lake)",
      'Treptower Park with Soviet war memorial',
      'Kayaking and outdoor activities',
      'Affordable rents with nature access',
      'Growing tech presence (Adlershof science park)',
    ],
  },
  {
    bezirk: 'marzahn-hellersdorf',
    displayName: 'Marzahn-Hellersdorf',
    vibe: 'East Berlin Plattenbau district being reinvented. Surprisingly green.',
    commuteMinutesMin: 25,
    commuteMinutesMax: 45,
    highlights: [
      'Gardens of the World (Gärten der Welt)',
      'Lowest rents in Berlin',
      'Large apartments at budget prices',
      'IGA park and green corridors',
      'Improving transit connections',
    ],
  },
  {
    bezirk: 'lichtenberg',
    displayName: 'Lichtenberg',
    vibe: 'Up-and-coming East Berlin. Vietnamese community hub with great food.',
    commuteMinutesMin: 12,
    commuteMinutesMax: 25,
    highlights: [
      'Dong Xuan Center (Vietnamese market)',
      "Tierpark Berlin (Europe's largest zoo by area)",
      'Affordable with improving infrastructure',
      'Growing creative scene',
      'Good S-Bahn and tram connections',
    ],
  },
  {
    bezirk: 'reinickendorf',
    displayName: 'Reinickendorf',
    vibe: 'Quiet northern district. Lakes, forests, and old Berlin charm.',
    commuteMinutesMin: 20,
    commuteMinutesMax: 45,
    highlights: [
      'Tegeler See (Tegel Lake)',
      'Former Tegel Airport area being redeveloped',
      'French Quarter (Alt-Tegel)',
      'Affordable rents with good amenities',
      'Greenwich Promenade waterfront',
    ],
  },
];

export const ALLOCATION: BudgetAllocation = {
  netMonthlySalary: 3500.0,
  bezirk: 'friedrichshain-kreuzberg',
  rooms: 2,
  categories: [
    {
      key: 'rent',
      label: 'Rent',
      percentage: 35.0,
      total: 1225.0,
      isCustom: false,
      pieGroup: 'housing',
      recommendedState: { minTotal: 880.0, percentage: 25.14 },
    },
    {
      key: 'utilities',
      label: 'Utilities',
      percentage: 5.0,
      total: 175.0,
      isCustom: false,
      pieGroup: 'housing',
      recommendedState: { minTotal: 192.5, percentage: 5.5 },
    },
    {
      key: 'transport',
      label: 'Transport',
      percentage: 3.0,
      total: 105.0,
      isCustom: false,
      pieGroup: 'essentials',
      recommendedState: { minTotal: 58.0, percentage: 1.66 },
    },
    {
      key: 'groceries',
      label: 'Groceries',
      percentage: 12.0,
      total: 420.0,
      isCustom: false,
      pieGroup: 'essentials',
      recommendedState: { minTotal: 300.0, percentage: 8.57 },
    },
    {
      key: 'dining',
      label: 'Dining',
      percentage: 8.0,
      total: 280.0,
      isCustom: false,
      pieGroup: 'lifestyle',
      recommendedState: null,
    },
    {
      key: 'savings',
      label: 'Savings',
      percentage: 20.0,
      total: 700.0,
      isCustom: false,
      pieGroup: 'financial',
      recommendedState: null,
    },
    {
      key: 'entertainment',
      label: 'Entertainment',
      percentage: 7.0,
      total: 245.0,
      isCustom: false,
      pieGroup: 'lifestyle',
      recommendedState: null,
    },
    {
      key: 'misc',
      label: 'Miscellaneous',
      percentage: 10.0,
      total: 350.0,
      isCustom: false,
      pieGroup: 'other',
      recommendedState: null,
    },
  ],
};
